plugins {
    id 'com.github.johnrengelman.shadow' version '8.1.1'
    id 'dev.architectury.loom' version '1.11.7'
}

architectury {
    platformSetupLoomIde()
    fabric()
}

configurations {
    common {
        canBeResolved = true
        canBeConsumed = false
    }
    compileClasspath.extendsFrom common
    runtimeClasspath.extendsFrom common
    developmentFabric.extendsFrom common

    shadowBundle {
        canBeResolved = true
        canBeConsumed = false
    }
}

dependencies {
    minecraft "com.mojang:minecraft:$rootProject.minecraft_version"
    mappings loom.officialMojangMappings()

    modImplementation "net.fabricmc:fabric-loader:$rootProject.fabric_loader_version"

    modImplementation fabricApi.module("fabric-networking-api-v1",     rootProject.fabric_api_version)
    modImplementation fabricApi.module("fabric-lifecycle-events-v1",   rootProject.fabric_api_version)
    modImplementation fabricApi.module("fabric-rendering-v1",          rootProject.fabric_api_version)
    modImplementation fabricApi.module("fabric-sound-api-v1",          rootProject.fabric_api_version)

    modImplementation "maven.modrinth:forge-config-api-port:${rootProject.forge_config_api_port_version}"
    include        "maven.modrinth:forge-config-api-port:${rootProject.forge_config_api_port_version}"

    modImplementation("dev.architectury:architectury-fabric:${rootProject.architectury_api_version}") {
        exclude group: "net.fabricmc.fabric-api", module: "fabric-api"
    }
    include "dev.architectury:architectury-fabric:${rootProject.architectury_api_version}"

    modImplementation "org.ladysnake.cardinal-components-api:cardinal-components-base:$rootProject.cardinal_components_version"
    modImplementation "org.ladysnake.cardinal-components-api:cardinal-components-entity:$rootProject.cardinal_components_version"
    include            "org.ladysnake.cardinal-components-api:cardinal-components-base:$rootProject.cardinal_components_version"
    include            "org.ladysnake.cardinal-components-api:cardinal-components-entity:$rootProject.cardinal_components_version"

    implementation "com.github.TartaricAlkaline:ImageStream:-SNAPSHOT"
    include        "com.github.TartaricAlkaline:ImageStream:-SNAPSHOT"

    modCompileOnly "com.terraformersmc:modmenu:$rootProject.modmenu_version"

    // YANG INI PALING PENTING SAYANG
    implementation project(':common')
    shadowBundle project(':common')
}

// BIAR SEMUA LIBRARY DI-INCLUDE KE SHADOW
configurations.shadowBundle.extendsFrom(configurations.include)

processResources {
    inputs.property 'version', project.version

    filesMatching('fabric.mod.json') {
        expand version: project.version
    }

    from(project(':common').sourceSets.main.resources)
    duplicatesStrategy = DuplicatesStrategy.INCLUDE
}

shadowJar {
    configurations = [project.configurations.shadowBundle]
    archiveClassifier = 'dev-shadow'
    mergeServiceFiles() // WAJIB BIAR MIXINS.JSON KE-MERGE
}

remapJar {
    input.set shadowJar.archiveFile
    archiveFileName = "yes-steve-model-${project.version}-fabric-${rootProject.minecraft_version}.jar"
}

loom {
    splitEnvironmentSourceSets()
}
