org.gradle.jvmargs=-Xmx3G
org.gradle.parallel=true
org.gradle.caching=true

# Mod properties
mod_version = 1.3.6-1.21.11
maven_group = rip.ysm
archives_name = fox-model-loader
enabled_platforms = fabric

# Minecraft
minecraft_version = 1.21.11
yarn_mappings = 1.21.11+build.1

# ====== VERSI FINAL YANG UDAH DI TES BUAT 1.21.11 ======
# Loom
architectury_loom_version = 1.14-SNAPSHOT

# Fabric
fabric_loader_version = 0.19.3
fabric_api_version = 0.141.6+1.21.11

# Library YSM - DITURUNIN BIAR COCOK SAMA MODS KAMU
architectury_api_version = 19.0.1+1.21.11
forge_config_api_port_version = 20.2.6+1.21.11

# Library lain
cardinal_components_version = 7.3.2
modmenu_version = 17.0.1-beta.1+1.21.11
geckolib_version = 5.4.5+1.21.11
