org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true

# Mod properties
mod_version = 1.3.6
maven_group = rip.ysm
archives_name = fox-model-loader
enabled_platforms = fabric

# Minecraft
minecraft_version = 1.21.11

# Fabric
fabric_loader_version = 0.19.3
fabric_api_version = 0.141.6+1.21.11

# Forge Config API Port (Fabric build for 1.21.11)
forge_config_api_port_version = 21.11.1

# Architectury API
architectury_api_version = 20.0.12
# Cardinal Components (v7 series untuk 1.21.11)
cardinal_components_version = 7.3.2

# Mod Menu
modmenu_version = 17.0.1-beta.1
