org.gradle.jvmargs=-Xmx3G
org.gradle.parallel=true

# Mod properties
mod_version = 1.3.6
maven_group = rip.ysm
archives_name = fox-model-loader
enabled_platforms = fabric

# Minecraft
minecraft_version = 1.21.11

# ====== VERSI ASLI & SYNC UNTUK 1.21.11 ======
# Versi Loom wajib dinaikkan ke 1.14 agar compiler tahu cara remap official Mojang ke Fabric
architectury_loom_version = 1.14-SNAPSHOT

# Versi Fabric Loader asli era 1.21.11
fabric_loader_version = 0.18.4
fabric_api_version = 0.141.6+1.21.11

# Forge Config API Port (Sesuai rilisan Fabric build 1.21.11)
forge_config_api_port_version = 21.11.1

# Architectury API resmi rilisan khusus 1.21.11
architectury_api_version = 19.0.1

# Cardinal Components (v7 series untuk 1.21.11)
cardinal_components_version = 7.3.2

# Mod Menu
modmenu_version = 17.0.1-beta.1
