architectury {
    common rootProject.enabled_platforms.split(',')
}

sourceSets.main.resources { srcDir 'src/generated/resources' }

dependencies {
    // Memuat pustaka dasar Minecraft sesuai versi properti yang ditentukan (1.21.11)
    minecraft "net.minecraft:minecraft:$rootProject.minecraft_version"
    
    mappings loom.officialMojangMappings()

    modImplementation "net.fabricmc:fabric-loader:$rootProject.fabric_loader_version"

    // TURUNIN KE 19.0.1 BIAR COCOK SAMA MODS KAMU
    modCompileOnly "dev.architectury:architectury:19.0.1"

    // TURUNIN KE 20.2.6 BIAR COCOK SAMA MODS KAMU V21.11.1
    modCompileOnly "maven.modrinth:forge-config-api-port:20.2.6"

    compileOnly "com.github.TartaricAlkaline:ImageStream:-SNAPSHOT"
}

// Native build (CMake) — DIMATIKAN.
tasks.register('compileNative') {
    enabled = false
    doLast {
        println "compileNative is disabled. Enable it manually if you have CMake + native toolchain."
    }
}

processResources.dependsOn compileNative

tasks.withType(JavaCompile).configureEach {
    options.failOnError = false
}
