- name: Upload JAR ke Releases
  if: success()
  uses: softprops/action-gh-release@v2
  with:
    files: |
      extracted/*/build/libs/*.jar
      build/libs/*.jar
    tag_name: "v1.0-${{ github.run_number }}"
    
